research_topic:
  description: >
    Recherchieren Sie das Thema des Romans "Unterm Rad" von Hermann Hesse, um die wichtigsten Informationen zu sammeln, die für die Erstellung einer Buchgliederung nützlich sind. 
    Stellen Sie sicher, dass Sie sich auf hochwertige, zuverlässige Quellen konzentrieren.

    Hier sind einige zusätzliche Informationen über das gewünschte Ziel des Autors für das Buch:\n\n {goal}
  expected_output: >
    Eine Sammlung von Schlüsselpunkten und wichtigen Informationen über den Roman "Unterm Rad", die zur Erstellung der Gliederung verwendet werden.
  agent: researcher

generate_outline:
  description: >
    Erstellen Sie eine Buchgliederung mit Kapiteln in der richtigen Reihenfolge basierend auf den Forschungsergebnissen. 
    Stellen Sie sicher, dass jedes Kapitel einen Titel und eine kurze Beschreibung enthält, die die Themen und Unterthemen hervorhebt, die behandelt werden sollen.
    Es ist wichtig zu beachten, dass jedes Kapitel nur 3.000 Wörter oder weniger umfassen wird.
    Stellen Sie außerdem sicher, dass Sie keine Kapitel oder Themen in der Gliederung duplizieren.

    Hier sind einige zusätzliche Informationen über das gewünschte Ziel des Autors für das Buch:\n\n {goal}

  expected_output: >
    Ein pydantisches Datenset von Kapiteln, die jeweils einen Titel (str) und eine Beschreibung (str) dessen enthalten, was jedes Kapitel im Buch enthalten wird. 
    Es dürfen keine Einleitungs- oder Schlusssätze geschrieben werden.
    Explizite Ausgabe ``{{"chapters":[{{"title"="aa","description"="bb"}},{{"title"="cc","description"="dd"}}] }}``
  agent: outliner
