research_chapter:
  description: >
    Recherchieren Sie das Thema des Romans "Unterm Rad" von Hermann Hesse, um die wichtigsten Informationen zu sammeln, die für die Erstellung einer Buchgliederung nützlich sind. 
    Stellen Sie sicher, dass Sie sich auf hochwertige, zuverlässige Quellen konzentrieren.

    Hier sind einige zusätzliche Informationen über das gewünschte Ziel des Autors für das Buch:\n\n {goal}
    Hier ist die Gliederungsbeschreibung für das Kapitel:\n\n {chapter_description}

    Beim Recherchieren sollten Sie die folgenden Schlüsselpunkte berücksichtigen:
    - Sie müssen genügend Informationen sammeln, um ein Kapitel von 3.000 Wörtern zu schreiben.
    - Das Kapitel, das Sie recherchieren, muss gut zu den anderen Kapiteln im Buch passen.

    Hier ist die Gliederung des gesamten Buches:\n\n
    {book_outline}
  expected_output: >
    Eine Sammlung zusätzlicher Erkenntnisse und Informationen, die beim Schreiben des Kapitels verwendet werden können.
  agent: researcher

write_chapter:
  description: >
    Schreiben Sie ein gut strukturiertes Kapitel basierend auf dem Kapiteltitel, Ziel und der Gliederungsbeschreibung. 
    Jedes Kapitel sollte im Markdown-Format geschrieben sein und etwa 3.000 Wörter enthalten.

    Hier ist das Thema des Buches: {topic}
    Hier ist der Titel des Kapitels: {chapter_title}
    Hier ist die Gliederungsbeschreibung für das Kapitel:\n\n {chapter_description}

    Wichtige Hinweise:
    - Das Kapitel, das Sie schreiben, muss gut zu den anderen Kapiteln im Buch passen.

    Hier ist die Gliederung des gesamten Buches:\n\n
    {book_outline}
  expected_output: >
    Eine genaue pydantische Liste, die Titel (str) und Inhalt (str) enthält.
    Der Inhalt enthält ein im Markdown-Format geschriebenes Kapitel von etwa 3.000 Wörtern, das den bereitgestellten Kapiteltitel und die Gliederungsbeschreibung abdeckt.
    Explizite Ausgabe ``{{"title"="aa","content"="bb"}}``
  agent: writer
